### ISSUE TITLE
Issue with all charts

### ISSUE THREAD

**Issue by Chandu-cuddle** [beto-rodriguez/Live-Charts#240]
In my project i am imported Livecharts through nuget.
Before i was using 0.7.0 version there is no problem. To day I upgraded to 0.7.4 and getting issue.

I can enter into charts page and i can access all charts, but when i am going to another pages i am getting below issue and exiting from application(application Closed automatically)

![image](https://cloud.githubusercontent.com/assets/17137255/16557443/83572e94-41e8-11e6-8743-b9da101e548e.png)

**Comment by beto-rodriguez** [comment]
Designer is crazy

Does your app runs? just press f5, it will run

then to fix the designer errors, close all files in visual studio, clean the solution and rebuild

**Comment by Chandu-cuddle** [comment]
Yes. I pressed F5, and its runs perfectly. The problem is when I move to other screen from Reports screen i am getting "**Argument Null Exception**" and its closing the application.

The reports Page is Like below: Working fine if i stay in that page only.
![image](https://cloud.githubusercontent.com/assets/17137255/16575755/54f1d79c-4293-11e6-9e3c-64e2ee0003fd.png)

I am getting below Issue  when i exit from reports page
![image](https://cloud.githubusercontent.com/assets/17137255/16575785/85ae91fe-4293-11e6-97db-27b44bc6e4fb.png)


So, i am downgraded to 0.7.0 version. Its working fine for me with 0.7.0. In 0.7.0 when i refresh the report the Legend colors or not refreshing. This was cleared in 0.7.4. But i am unable to use 0.7.4.

Anyway thank you for your support.

**Comment by beto-rodriguez** [comment]
I will investigate the issue, thanks for reporting

**Comment by RambaaZambaa** [comment]
I had a simmilar issue (NullReferenceException in the designer).
Removing the following line in XAML solves the problem while obviously removing the legend, which i need:
 LegendLocation=" whatever "

**Comment by beto-rodriguez** [comment]
@Chandu-cuddle you were right 0.7.4.1 should solve your issue, please let me know if it does not

**Comment by Chandu-cuddle** [comment]
I tried with 0.7.4.1. Still I  am getting same issue.
Please find the below screenshot.

![image](https://cloud.githubusercontent.com/assets/17137255/16708224/88314882-45f3-11e6-8262-741d274d4a14.png)

**Comment by beto-rodriguez** [comment]
Can you please give me the full excepción? Click at copy full exception and paste it here please it would help me a lot

**Comment by Chandu-cuddle** [comment]
System.ArgumentNullException was unhandled
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: source
  ParamName=source
  Source=System.Core
  StackTrace:
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
       at LiveCharts.Charts.PieChartCore.PrepareAxes()
       at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
       at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView)
       at LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
       at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at Cuddle.Presentation.App.Main() in C:\Users\Shashank\Downloads\Compressed\Cuddle\obj\x86\Debug\App.g.cs:line 0
  InnerException:

**Comment by mikeb86** [comment]
I had the same issue using 0.7.5.1, this occurred when I had multiple line graphs in my WPF app that had a legend displayed. _Sometimes_ the legend would render correctly, while other times I received an unhandled exception. Here's the stack trace of the exception: 

Error : Error: Object reference not set to an instance of an object.
Stack Trace:    at LiveCharts.Wpf.Charts.Base.Chart.LoadLegend()
   at LiveCharts.Charts.ChartCore.PlaceLegend(CoreRectangle drawMargin)
   at LiveCharts.Charts.ChartCore.CalculateComponentsAndMargin()
   at LiveCharts.Charts.CartesianChartCore.PrepareAxes()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView)
   at LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Here's the screenshot 
![7-12-2016 4-24-47 pm](https://cloud.githubusercontent.com/assets/20426992/16782418/7bcc1520-484d-11e6-8074-6575ad4d59db.png)

**Comment by beto-rodriguez** [comment]
Finally I was able to debuged the designer, last release should fix many issues mentioned here, I practically saw all these stack traces while fixing this.

It would be very useful if you all could try 0.7.6 and let me know if everything is working correctly for you.

Hope this release fixes all these issues https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.7.6

**Comment by Chandu-cuddle** [comment]
Yes @beto-rodriguez . 
My Issue is Solved. Thank you so much for your support.

**Comment by RambaaZambaa** [comment]
Mine aswell. Thank you!

**Comment by mikeb86** [comment]
My issue is resolved as well! Thanks so much!

**Comment by beto-rodriguez** [comment]
Thanks everyone for testing!

**Comment by FarfetchdB** [comment]
Hi, I still have the same issue.

In LiveCharts for Wpf version 0.9.7, same Exception (ArgumentNullException) is thrown in Visual Studio Designer.

Removing the line `Sections="{Binding MyProperty}"` from the `Axis` tag resolves the Exception.

**Comment by davidemess** [comment]
Hi, 
I have this issue too with LiveCharts.Wpf 0.9.7.

```
<lvc:PieChart LegendLocation="Right" Grid.Column="1" Name="pieChart">
    <lvc:PieChart.Series>
        <lvc:PieSeries Name="chartSeries1"/>
        <lvc:PieSeries Name="chartSeries2"/>
        <lvc:PieSeries Name="chartSeries4"/>
    </lvc:PieChart.Series>
</lvc:PieChart>
```
