### ISSUE TITLE
Unable to style DataLabels

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/Live-Charts#277]
Setting 

    Series.FontSize = 20;

Should change the font style of the data labels in the series, this feature is not working correctly in the latest version.

**Comment by beto-rodriguez** [comment]
@RambaaZambaa Thanks for the report, this is already fixed and will be included in next release

**Comment by Showmaster3000** [comment]
I think the problem still persists, I use the latest version from nuget 0.7.10
The FontSize property is also ignored on AxisX and AxisY.
I use for example the following code:

`CC_Chart1.AxisX.Add(new Axis`
`            {`
`                LabelFormatter = val => TimeSpan.FromSeconds(val).ToString(@"mm\:ss"),`
`                //FontStyle = System.Windows.FontStyles.Italic,`
`                //FontWeight = System.Windows.FontWeights.ExtraBold,`
`                FontSize = 30,`
`                Separator = new Separator`
`                {`
`                    Step = 5`
`                }`

FontStyle, FontWeight, FontFamily are set as expected.

**Comment by beto-rodriguez** [comment]
@Showmaster3000 you are right, it was being ignored for axes, last commit fixes it, it will be included in next release 0.7.11
