### ISSUE TITLE
Visibility doesn't work

### ISSUE THREAD

**Issue by FoggyFinder** [beto-rodriguez/Live-Charts#307]
Visibility doesn't work.
Example:

```
<Window 
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf" ...>
    <Window.Resources>
        <BooleanToVisibilityConverter x:Key="b2v"/>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"></RowDefinition>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition Height="Auto"></RowDefinition>
        </Grid.RowDefinitions>
        <lvc:CartesianChart>
            <lvc:CartesianChart.AxisY>
                <lvc:Axis Foreground="DodgerBlue" Title="Blue Axis" Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"  />
                <lvc:Axis Foreground="IndianRed" Title="Red Axis" Position="RightTop" Separator="{x:Static lvc:DefaultAxes.CleanSeparator}" Visibility="{Binding ElementName=red,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"  />
                <lvc:Axis Foreground="DarkOliveGreen" Title="Green Axis" Position="RightTop" Separator="{x:Static lvc:DefaultAxes.CleanSeparator}" Visibility="{Binding ElementName=green,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"  />
            </lvc:CartesianChart.AxisY>
            <lvc:CartesianChart.Series>
                <lvc:LineSeries Values="1,5,3,5,3" ScalesYAt="0" Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"  />
                <!--Scales at blue axis, Axis[0]-->
                <lvc:LineSeries Values="20,30,70,20,10"  ScalesYAt="1" Visibility="{Binding ElementName=red,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"  />
                <!--Scales at red axis, Axis[1]-->
                <lvc:LineSeries Values="600,300,200,600,800"  ScalesYAt="2" Visibility="{Binding ElementName=green,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"  />
                <!--Scales at green axis, Axis[2]-->
            </lvc:CartesianChart.Series>
        </lvc:CartesianChart>
        <TextBlock Grid.Row="1" HorizontalAlignment="Right" Text="Blue"
                   Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"
                   ></TextBlock>
        <CheckBox Grid.Row="1" Name="blue" Content="Blue"></CheckBox>
        <CheckBox Grid.Row="2" Name="red" Content="Red"></CheckBox>
        <CheckBox Grid.Row="3" Name="green" Content="Green"></CheckBox>
    </Grid>
</Window>
```

**Comment by beto-rodriguez** [comment]
Just tested the example in the repo and it is working correctly, I will try your code latter, but please see the example in the repo, it works

**Comment by beto-rodriguez** [comment]
OK I got the error, working on it

**Comment by beto-rodriguez** [comment]
Last commit should fix it, for more info see #298 

I will include this fix in 0.7.12 version, you can also close and let me know if this does not solves your issue, thanks for reporting

**Comment by FoggyFinder** [comment]
Seems, bug is not fixed:
![1](https://cloud.githubusercontent.com/assets/16510738/18087794/f8c4628a-6ec7-11e6-9f87-61d9b64f1c89.png)

**Comment by beto-rodriguez** [comment]
version?

**Comment by FoggyFinder** [comment]
Last - 0.7.12

**Comment by beto-rodriguez** [comment]
I see the issue, you were right it was not fixed.

**Comment by beto-rodriguez** [comment]
**Workaround** use a property to control the visibility of both items as shown [here](https://lvcharts.net/App/examples/v1/wpf/Dynamic%20Visibility)

For some unknown reason I get:

> System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=blue'. BindingExpression:Path=IsChecked; DataItem=null; target element is 'LineSeries' (Name='Series'); target property is 'Visibility' (type 'Visibility')

with:

```xml
<Grid>
            <Grid.Resources>
                <local:VisibilityConverter x:Key="b2v"/>
            </Grid.Resources>
            <Grid.RowDefinitions>
                <RowDefinition Height="250"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
            <lvc:CartesianChart MouseDoubleClick="Control_OnMouseDoubleClick">
                <lvc:CartesianChart.AxisY>
                    <lvc:Axis Foreground="DodgerBlue" Title="Blue Axis" />
                </lvc:CartesianChart.AxisY>
                <lvc:CartesianChart.Series>
                    <lvc:LineSeries Name="Series" Values="1,5,3,5,3" ScalesYAt="0" 
                        Visibility="{Binding ElementName=blue,
                        Converter={StaticResource ResourceKey=b2v},
                        Path=IsChecked,
                        PresentationTraceSources.TraceLevel=High}"  />
                </lvc:CartesianChart.Series>
            </lvc:CartesianChart>
            <TextBlock Grid.Row="1" HorizontalAlignment="Right" Text="Blue"
                   Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"></TextBlock>
            <StackPanel Grid.Row="1" Orientation="Horizontal">
                <CheckBox Name="blue" Content="Blue"></CheckBox>
                <TextBlock  Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}">delete me</TextBlock>
            </StackPanel>
        </Grid>
```

**Comment by beto-rodriguez** [comment]
I am not completely sure if this is a bug in the library, I examined the visual tree and everything seems to be correct.

Actually I found a question in SO with a similar issue:

https://stackoverflow.com/questions/9122592/elementname-binding-is-failing

This worked for me, I am closing this for now, specifying the source property of the binding made it work for me, this introduced a new issue, I'll keep this open to remind me to fix it:

```
<Grid>
            <Grid.Resources>
                <BooleanToVisibilityConverter x:Key="b2v"/>
            </Grid.Resources>
            <Grid.RowDefinitions>
                <RowDefinition Height="250"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
            <lvc:CartesianChart>
                <lvc:CartesianChart.Series>
                    <lvc:LineSeries Name="Series" Values="1,5,3,5,3" 
                                    Visibility="{Binding Source={x:Reference blue},
                        Converter={StaticResource ResourceKey=b2v},
                        Path=IsChecked,
                        PresentationTraceSources.TraceLevel=High}"  />
                </lvc:CartesianChart.Series>
            </lvc:CartesianChart>
            <TextBlock Grid.Row="1" HorizontalAlignment="Right" Text="Blue"
                       Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}"></TextBlock>
            <StackPanel Grid.Row="1" Orientation="Horizontal">
                <CheckBox Name="blue" Content="Blue"></CheckBox>
                <TextBlock  Visibility="{Binding ElementName=blue,Converter={StaticResource ResourceKey=b2v},Path=IsChecked}">delete me</TextBlock>
            </StackPanel>
```

**Comment by beto-rodriguez** [comment]
The referenced commit fixes the visibility issue.

And the workaround is clean and good enough to close this issue, the fix will be published with version 0.9.7

Thanks for the report
