### ISSUE TITLE
When the mouse constantly slides on PieChat, the section goes off.

### ISSUE THREAD

**Issue by abraaocaldas** [beto-rodriguez/Live-Charts#317]
When the mouse constantly slides on PieChat, the section you are sliding fly off.

LiveCharts.WPF 0.7.11

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3661806/18017858/9741ef92-6ba1-11e6-916a-1f850d8c8b41.gif)

PS: there is any suite to record screen and save as gif, I saw it a lot of times here (gif creation)

**Comment by beto-rodriguez** [comment]
does it comes back to its original position?

**Comment by abraaocaldas** [comment]
Nope, , it tries to get back to original position but stop on the mid of path, so the next time it will start from there and keeps going....

**Comment by beto-rodriguez** [comment]
I will take a look.

About the recorder I use [LICEcap](http://www.cockos.com/licecap/)

**Comment by beto-rodriguez** [comment]
Hello, are you using 0.7.11?, I can not reproduce this error, I similar issue was fixed with #272

**Comment by abraaocaldas** [comment]
Yes, I´m using version v0.7.11

**Comment by abraaocaldas** [comment]
Hello, I´m using now version 0.7.13 the problem persists.

Here is how I´m doing it.

```
private` PieSeries freeMemory = new PieSeries();
private PieSeries usedMemory = new PieSeries();
public SeriesCollection DonutCollection { get; set; }

DonutCollection = new SeriesCollection
            {
               freeMemory,
               usedMemory
            };
```

Then I have a method to update the values from another class that have an Instance of my class.

```
public void ReceiveData(string message)
        {
            MemoryModel model = JsonConvert.DeserializeObject<MemoryModel>(message);

            double free = double.Parse(Regex.Match(model.MemFree, @"\d+").Value);
            double used = double.Parse(Regex.Match(model.Active, @"\d+").Value);

            Dispatcher.Invoke(() =>
            {
                freeMemory.Values.Cast<ObservableValue>().First().Value = free;
                usedMemory.Values.Cast<ObservableValue>().First().Value = used;
            });

        }
```

No, that I update the values each 300ms interval, sometimes faster.

**Comment by beto-rodriguez** [comment]
I see the error, an alternative for now is disable the hovering in your chart 

     <lvc:PieChart Grid.Row="1" Hoverable="False">
        </lvc:PieChart>

**Comment by beto-rodriguez** [comment]
This is already fixed and will be included since 0.7.14, thanks for the report
