### ISSUE TITLE
Crash when resizing window containing chart

### ISSUE THREAD

**Issue by DeadlyEmbrace** [beto-rodriguez/Live-Charts#444]
#### How to reproduce?

See [this](https://github.com/DeadlyEmbrace/LiveChartCrash) repository for crash replication. Simply hit the resize button.
In the application proper it happens when the window is pulled from a maximized space squashing the chart down to zero size, but the effect is the same.

#### Extra notes

Occurs in the [Move()](https://github.com/beto-rodriguez/Live-Charts/blob/master/WpfView/Components/AxisSeparatorElement.cs#L173)  method of the AxistSeperatorElement.cs class if any of the double parameter values (toLabel, toLine, tab) are NaN. Not sure how the value gets to be NaN, but seems to happen when the size of the Chart container is set to 0

Original crash report:
```
System.ArgumentException: 'NaN' is not a valid value for property 'To'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
   at LiveCharts.Wpf.Components.AxisSeparatorElement.Move(ChartCore chart, AxisCore axis, AxisOrientation direction, Int32 axisIndex, Double toLabel, Double toLine, Double tab)
   at LiveCharts.AxisCore.UpdateSeparators(AxisOrientation source, ChartCore chart, Int32 axisIndex)
   at LiveCharts.Charts.ChartCore.CalculateComponentsAndMargin()
   at LiveCharts.Charts.CartesianChartCore.PrepareAxes()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.90.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>462</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This is now fixed and included in v 091, thanks for the report and repo!

**Comment by DeadlyEmbrace** [comment]
Awesome, thank you!

**Comment by Shinjoku** [comment]
I got a very similar problem today, but it was totally my fault. It's pretty obvious that the axis Y range can't be 0, but at the error moment I wasn't thinking about it.
This error still happening when we set the value of the separator to 0 arbitrarily. The app crashes and leave behind the same exception, without saying which line triggered it.


|  App  | Version |
| ------------- | ------------- |
| LiveCharts | 0.9.7  |
| Windows | 10 |
